services:
  db:
    image: mariadb:10.9
    restart: always
    ports:
      - 127.0.0.1:3317:3306
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: parts
    volumes:
      - ./data:/var/lib/mysql

  backup:
    image: periodic-backup
    build: periodic-backup
    restart: always
    volumes:
      - ~/Dropbox/partsTrackr/:/backup

  backend:
    image: parts-tracker
    build: backend
    restart: always
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mariadb://db/parts
      - DOCUMENTS_PATH=/data
    volumes:
      - ~/Dropbox/partsTrackr/documents:/data

  web:
    image: parts-tracker-web
    build: web
    restart: always
    ports:
      - 127.0.0.1:7080:8080
